import Head from "next/head";
import Courses from "../components/common/Courses";
import {Menu, Text} from "../components/common/Menu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu/>
      <Text/>
      <Courses/>
    </div>
  );
}
